name: Continuous Integration

on:
  schedule:
    - cron: '3/15 * * * *'

jobs:
  build:
    name: build and test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install node_modules
        run: npm install
      - name: test
        run: npm run test:ci
      - name: build
        run: npm run build